drop table if exists customer;
drop table if exists hibernate_sequence;
drop table if exists location;
drop table if exists order_details;
drop table if exists orders;
drop table if exists product;
drop table if exists product_suppliers;
drop table if exists product_category;
drop table if exists revenue;
drop table if exists stock;
drop table if exists stock_prod;
drop table if exists supplier;
create table customer (id integer not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), user_name varchar(255), primary key (id)) engine=MyISAM;
create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table location (id integer not null, city varchar(255), country varchar(255), county varchar(255), street_address varchar(255), name varchar(255), primary key (id)) engine=MyISAM;
create table order_details (id integer not null, quantity integer, order_id integer, product_id integer, primary key (id)) engine=MyISAM;
create table orders (id integer not null, city varchar(255), country varchar(255), county varchar(255), street_address varchar(255), created_at datetime, customer_id integer, shipped_from_id integer, primary key (id)) engine=MyISAM;
create table product (id integer not null, description varchar(255), name varchar(255), price decimal(19,2), weight double precision, pc_id integer, primary key (id)) engine=MyISAM;
create table product_suppliers (product_id integer not null, suppliers_id integer not null) engine=MyISAM;
create table product_category (id integer not null, department varchar(255), name varchar(255), primary key (id)) engine=MyISAM;
create table revenue (id integer not null, date date, sum decimal(19,2), location_id integer, primary key (id)) engine=MyISAM;
create table stock (id integer not null, quantity integer, loc_id integer, primary key (id)) engine=MyISAM;
create table stock_prod (stock_id integer not null, prod_id integer not null) engine=MyISAM;
create table supplier (id integer not null, name varchar(255), primary key (id)) engine=MyISAM;
alter table stock_prod add constraint UK_6bveya9oa3d2k18na3e7goy83 unique (prod_id);
alter table order_details add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk foreign key (order_id) references orders (id);
alter table order_details add constraint FKinivj2k1370kw224lavkm3rqm foreign key (product_id) references product (id);
alter table orders add constraint FK624gtjin3po807j3vix093tlf foreign key (customer_id) references customer (id);
alter table orders add constraint FKftf58a58sqnkcw7h7b5dbmgst foreign key (shipped_from_id) references location (id);
alter table product add constraint FK7vts0rmwgsrnp9rbaunxmq1tf foreign key (pc_id) references product_category (id);
alter table product_suppliers add constraint FK5mivv19b0g9lhvsoho3po4cmo foreign key (suppliers_id) references supplier (id);
alter table product_suppliers add constraint FK25qaqugu4rwup73wmfbh3glk foreign key (product_id) references product (id);
alter table revenue add constraint FK6xukepd8ssa1ok6iakkhp83p7 foreign key (location_id) references location (id);
alter table stock add constraint FKi4o32t04fmyyjg9fsuknj7jym foreign key (loc_id) references location (id);
alter table stock_prod add constraint FKe7gkufpmohfajpmjgqsj6mqpt foreign key (prod_id) references product (id);
alter table stock_prod add constraint FKg5ua5oewtwper2sixvia3orc0 foreign key (stock_id) references stock (id);